export const FETCH_BLOG_PENDING = 'FETCH_BLOG_PENDING';
export const FETCH_BLOG_FULFILLED = 'FETCH_BLOG_FULFILLED';
export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_BLOG_REJECTED = 'FETCH_BLOG_REJECTED';
