export const ADD_COMMENT = 'ADD_COMMENT';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_END = 'FETCH_COMMENTS_END';
export const SHOW_COMMENT = 'SHOW_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
