export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULFIllED = 'FETCH_USERS_FULFIllED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
